Repository yahoo/ychaos, pull requests merged in 2021-08, with the labels that each got.

#32 Increase project coverage, Project Metadata fixes
  screwdriver.yaml
  screwdriver/codecov.sh
  screwdriver/semgrep.sh
  setup.cfg
  src/ychaos/agents/index.py
  src/ychaos/agents/utils/sysctl.py
  src/ychaos/core/executor/MachineTargetExecutor.py
  tests/agents/network/test_TrafficBlock.py
  tests/cli/test_exceptions.py
Labels: CI Pipeline, best-practices

#33 Remove the requirement of virtualenv package on remote by using venv
  docs/get_started.md
  docs/index.md
  docs/releases.md
  src/ychaos/core/executor/MachineTargetExecutor.py
  tests/core/executor/test_MachineTargetExecutor.py
Labels: enhancement, ychaos-executor

#43 Version 0.2.0 release
  docs/releases.md
  setup.cfg
Labels: enhancement, CI Pipeline

#35 Adding disk fill agent
  src/ychaos/agents/index.py
  src/ychaos/agents/system/disk.py
  src/ychaos/testplan/resources/schema.json
  tests/agents/system/test_disk.py
Labels: enhancement, ychaos-agents

#44 Adding doc for disk fill agent
  docs/package_docs/agents/system/.pages
  docs/package_docs/agents/system/disk.md
  docs/releases.md
Labels: documentation

#42 Add Schema for OpenTSDB verification plugin
  docs/package_docs/testplan/.pages
  docs/package_docs/testplan/verification/.pages
  docs/package_docs/testplan/verification/index.md
  docs/package_docs/testplan/verification/plugins/.pages
  docs/package_docs/testplan/verification/plugins/metrics.md
  setup.cfg
  src/ychaos/testplan/resources/schema.json
  src/ychaos/testplan/verification/__init__.py
  src/ychaos/testplan/verification/plugins/__init__.py
  src/ychaos/testplan/verification/plugins/metrics.py
  src/ychaos/utils/builtins.py
  tests/resources/testplans/valid/testplan6.yaml
  tests/resources/testplans/valid/testplan7.yaml
  tests/resources/testplans/valid/testplan8.yaml
  tests/testplan/test_metrics.py
  tests/utils/test_builtins.py
Labels: enhancement, ychaos-verification

#52 Fix Type Validation for mypy > 0.900
  setup.cfg
Labels: CI Pipeline, dependencies

#55 Integrate codespell to the repository
  develop/build.sh
  docs/agents/index.md
  docs/cli/index.md
  screwdriver.yaml
  setup.cfg
  src/ychaos/testplan/verification/__init__.py
  tests/cli/test_exceptions.py
Labels: CI Pipeline, best-practices

#57 Add No-Color Docs to FAQ
  docs/faq.md
  src/ychaos/cli/main.py
Labels: documentation
