Repository yahoo/ychaos, pull requests merged in 2021-09, with the labels that each got.

#61 Try Python3.10 support
  .gitignore
  screwdriver.yaml
Labels: enhancement, CI Pipeline, best-practices

#64 Fix importing not-needed PyOpenSSL dependency
  docs/releases.md
  src/ychaos/agents/validation/certificate.py
  src/ychaos/utils/dependency.py
  tests/agents/validation/test_CertificateFileValidation.py
  tests/utils/test_dependency.py
Labels: bug

#59 Add Callable Mapping to Hooks
  docs/testplan/schema/README.md
  src/ychaos/agents/coordinator.py
  src/ychaos/core/executor/MachineTargetExecutor.py
  src/ychaos/core/verification/controller.py
  src/ychaos/utils/hooks.py
Labels: enhancement, refactor

#66 Add documentation for HTTP Request & SDv4 verification plugin
  develop/build.sh
  docs/verification/.pages
  docs/verification/plugins/.pages
  docs/verification/plugins/http_request.md
  docs/verification/plugins/python_module.md
  docs/verification/plugins/sdv4.md
  screwdriver.yaml
Labels: documentation

#67 refactor delay_before after checking state
  docs/testplan/sample_test_plan.md
  src/ychaos/core/verification/controller.py
  tests/core/verification/test_controller.py
Labels: bug

#70 Handle dump yaml/json File not found error
  src/ychaos/cli/verify.py
  src/ychaos/core/verification/controller.py
  tests/cli/test_verify.py
  tests/core/verification/test_controller.py
Labels: bug

#65 Implement OpenTSDB Verification Plugin for Criteria
  src/ychaos/core/verification/plugins/BaseVerificationPlugin.py
  src/ychaos/core/verification/plugins/HTTPRequestVerificationPlugin.py
  src/ychaos/core/verification/plugins/OpenTSDBVerificationPlugin.py
  src/ychaos/testplan/verification/__init__.py
  tests/core/verification/plugins/test_OpenTSDBVerificationPlugin.py
Labels: enhancement, ychaos-verification
