Repository yahoo/ychaos, pull requests merged in 2021-07, with the labels that each got.

#37 Add Sample Testplans to Documentation
  docs/testplan/.pages
  docs/testplan/sample_test_plan.md
Labels: documentation

#38 Fix doc link in README.md
  README.md
Labels: documentation

#39 Fix pushing tags during release
  screwdriver.yaml
Labels: CI Pipeline

#41 Add new hook `on_plugin_not_found` for Verification Controller
  Makefile
  docs/releases.md
  src/ychaos/cli/verify.py
  src/ychaos/core/verification/controller.py
  src/ychaos/testplan/resources/schema.json
  src/ychaos/testplan/verification.py
  tests/cli/test_verify.py
  tests/core/verification/test_controller.py
  tests/resources/testplans/valid/testplan6.yaml
Labels: bug, ychaos-cli, ychaos-verification

#40 Adding "Disable Ping" Agent to schema
  docs/package_docs/agents/system/.pages
  docs/package_docs/agents/system/icmp.md
  src/ychaos/agents/index.py
  src/ychaos/testplan/resources/schema.json
Labels: ychaos-schema
