Repository yahoo/ychaos, pull requests merged in 2021-11, with the labels that each got.

#83 Publish docker image with ychaos pre-installed
  Dockerfile
  screwdriver.yaml
Labels: enhancement, CI Pipeline

#85 containerize ychaos with multiple python version
  Dockerfile
  screwdriver.yaml
Labels: enhancement, CI Pipeline

#86 Enable SD docker-in-docker
  screwdriver.yaml
Labels: enhancement, CI Pipeline

#87 Publish ychaos images on each release
  docs/index.md
  screwdriver.yaml
Labels: documentation, enhancement, CI Pipeline

#89 Push latest docker tag to Docker hub
  screwdriver.yaml
Labels: enhancement, CI Pipeline

#88 Add 'all' as the way to install both chaos and agents subpackage together
  Dockerfile
  docs/index.md
  setup.cfg
Labels: dependencies

#84 Documentation for SelfTargetExecutor
  docs/package_docs/core/executor/.pages
  docs/package_docs/core/executor/SelfTargetExecutor.md
  docs/testplan/sample_test_plan.md
  docs/testplan/target_spec.md
  src/ychaos/testplan/attack.py
Labels: documentation

#92 Add support to SSH common args in TestPlan, make SSH config optional
  src/ychaos/testplan/attack.py
Labels: enhancement
